Models/Attend.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Attendance.Models
{
    public class Attend
    {
        public int EmpID { get; set; }
        public string Name { get; set; }

        [DataType(DataType.Date)]
        public DateTime Date { get; set; }
        public String Attendance { get; set; }

    }
}

Controllers/AttendController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.SqlClient;
using Attendance.Models;
using Rotativa;

namespace Attendance.Controllers
{
    public class AttendController : Controller
    {
        string connectionString = @"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=HRM;Integrated Security=True";
        // GET: Attend
        public ActionResult Index()
        {
            DataTable dtblAttend = new DataTable();
            using (SqlConnection sqlcon = new SqlConnection(connectionString))
            {
                sqlcon.Open();
                SqlDataAdapter sqlda = new SqlDataAdapter("SELECT * FROM Attend", sqlcon);
                sqlda.Fill(dtblAttend);
            }
            return View(dtblAttend);
        }

        public ActionResult Print()
        {
            var report = new ActionAsPdf("Index");
            return report;
        }

        // GET: Attend/Create
        public ActionResult Create()
        {

            return View(new Attend());
        }

        // POST: Attend/Create
        [HttpPost]
        public ActionResult Create(Attend attend)
        {
            using (SqlConnection sqlcon = new SqlConnection(connectionString))
            {
                sqlcon.Open();
                string query = "INSERT INTO Attend VALUES (@Name,@Date,@Attendance)";
                SqlCommand sqlcmd = new SqlCommand(query,sqlcon);
                sqlcmd.Parameters.AddWithValue("@Name", attend.Name);
                sqlcmd.Parameters.AddWithValue("@Date", attend.Date);
                sqlcmd.Parameters.AddWithValue("@Attendance", attend.Attendance);
                sqlcmd.ExecuteNonQuery();
            }
           return RedirectToAction("Index");
        }

        // GET: Attend/Edit/5
        public ActionResult Edit(int id)
        {
            Attend attend = new Attend();
            DataTable dtblAttend = new DataTable();
            using (SqlConnection sqlcon = new SqlConnection(connectionString))
            {
                sqlcon.Open();
                string query = "SELECT * FROM Attend where EmpID = @EmpID";
                SqlDataAdapter sqlda = new SqlDataAdapter(query, sqlcon);
                sqlda.SelectCommand.Parameters.AddWithValue("EmpID", id);
                sqlda.Fill(dtblAttend);
            }
             if(dtblAttend.Rows.Count == 1)
            {
                attend.EmpID = Convert.ToInt32(dtblAttend.Rows[0][0].ToString());
                attend.Name = (dtblAttend.Rows[0][1].ToString());
                attend.Date = Convert.ToDateTime(dtblAttend.Rows[0][2].ToString());
                attend.Attendance = (dtblAttend.Rows[0][3].ToString());
                return View(attend);
            }
             return RedirectToAction("Index");
        }

        // POST: Attend/Edit/5
        [HttpPost]
        public ActionResult Edit(Attend attend)
        {
            using (SqlConnection sqlcon = new SqlConnection(connectionString))
            {
                sqlcon.Open();
                string query = "UPDATE Attend SET Name = @Name, Date = @Date, Attendance = @Attendance where EmpID = @EmpID";
                SqlCommand sqlcmd = new SqlCommand(query, sqlcon);
                sqlcmd.Parameters.AddWithValue("@EmpID", attend.EmpID);
                sqlcmd.Parameters.AddWithValue("@Name", attend.Name);
                sqlcmd.Parameters.AddWithValue("@Date", attend.Date);
                sqlcmd.Parameters.AddWithValue("@Attendance", attend.Attendance);
                sqlcmd.ExecuteNonQuery();
            }

            return RedirectToAction("Index");
        }

        // GET: Attend/Delete/5
        public ActionResult Delete(int id)
        {
            using (SqlConnection sqlcon = new SqlConnection(connectionString))
            {
                sqlcon.Open();
                string query = "DELETE FROM Attend where EmpID = @EmpID";
                SqlCommand sqlcmd = new SqlCommand(query, sqlcon);
                sqlcmd.Parameters.AddWithValue("@EmpID", id);
                sqlcmd.ExecuteNonQuery();
            }
            return RedirectToAction("Index");
        }
        public ActionResult LogOut()
        {
            return RedirectToAction("LogOut");
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Attendance.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Views/Attend/Create.cshtml
@model Attendance.Models.Attend

@{
    ViewBag.Title = "Create";
}

<h3>Create Attendance</h3>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.EmpID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Attendance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Attendance, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Attendance, "", new { @class = "text-danger" })*@
                Present: @Html.RadioButton("Attendance", "Present")
                Absent: @Html.RadioButton("Attendance", "Absent")
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<style type="text/css">
    h3 {
        height: 30px;
        width: 100%;
        text-align: center;
    }

    .form-group {
        padding: 8px;
        width: 250%
    }

    .form-horizontal {
        border: 2px solid gray;
        border-width: 10px;
        width: 100%;
        border-radius: 20px;
        background-color: #DAF7A6;
    }
</style>

Views/Attend/Edit.cshtml
@model Attendance.Models.Attend

@{
    ViewBag.Title = "Edit";
}

<h3>Edit Attendance</h3>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EmpID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.EmpID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.EmpID, "", new { @class = "text-danger" })*@
                @Html.DisplayFor((model) => model.EmpID)
                @Html.HiddenFor((model) => model.EmpID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })*@
                @Html.DisplayFor((model) => model.Name)
                @Html.HiddenFor((model) => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Attendance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Attendance, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Attendance, "", new { @class = "text-danger" })*@
                Present: @Html.RadioButton("Attendance", "Present")
                Absent: @Html.RadioButton("Attendance", "Absent")
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-warning" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Attendance List", "Index")
</div>
<style text-align: center; type="text/css">
    table {
        border-collapse: collapse;
        width: 100%;
    }

    th, tr, td {
        padding: 8px;
        text-align: center;
        border-bottom: 1px solid #ddd;
    }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }

    element.style {
        text-align: center;
    }
</style>


<style text-align: center; type="text/css">
    h3 {
        height: 30px;
        width: 100%;
    }

    .form-group {
        padding: 8px;
        width: 200%
    }

    .form-horizontal {
        border: 2px solid gray;
        border-width: 100;
        width: 60%;
        border-radius: 20px;
        background-color: #DAF7A6;
    }

    element.style {
        text-align: center;
    }
</style>

Views/Attend/Index.cshtml
@model System.Data.DataTable
@{
    ViewBag.Title = "Index";
}

<table class="table table-bordered table-striped table-hover">
    <tr>
        <th>EmpID</th>
        <th>Name</th>
        <th>Date</th>
        <th>Attendance</th>
        <th>Options</th>
    </tr>
    @for (int i = 0; i < Model.Rows.Count; i++)
    {
        <tr>
            <td>@Model.Rows[i][0]</td>
            <td>@Model.Rows[i][1]</td>
            <td>@Model.Rows[i][2]</td>
            <td>@Model.Rows[i][3]</td>
            <td>
                <a href="@Url.Action("Edit","Attend", new { @id = Model.Rows[i][0] })">Edit</a> |
                <a href="@Url.Action("Delete","Attend", new { @id = Model.Rows[i][0] })">Delete</a>
            </td>
        </tr>
    }
</table>
<a href="@Url.Action("Create","Attend")">Add Attendance</a>

<style text-align: center; type="text/css">
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    td, th {
        padding: 15px;
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }

    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
    }

    th, td {
        padding: 15px;
        text-align: left;
    }

    table {
        background-color: #f1f1c1;
    }

        table tr:nth-child(even) {
            background-color: #eee;
        }

        table tr:nth-child(odd) {
            background-color: #fff;
        }

        table th {
            background-color: black;
            color: white;
        }

    p {
        background-color: #eee;
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    table.center {
        margin-left: auto;
        margin-right: auto;
    }

    body {
        text-align: center;
    }

    table {
        margin-left: auto;
        margin-right: auto;
    }
</style>
<body style="background-color:#E6E6FA;">
</body>

Views/Attend/LogOut.cshtml
@model Attendance.Models.Attend

@{
    ViewBag.Title = "LogOut";
}

<h2>LogOut</h2>

Views/Attend/Print.cshtml
@model IEnumerable<Attendance.Models.Attend>

@{
    ViewBag.Title = "Print";
}

<h2>Print</h2>

<p>
    @Html.ActionLink("Print", "Print")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EmpID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Attendance)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EmpID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Attendance)
            </td>
        </tr>
    }
</table>
<style text-align: center; type="text/css">
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    td, th {
        padding: 15px;
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }

    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
    }

    th, td {
        padding: 15px;
        text-align: left;
    }

    table {
        background-color: #f1f1c1;
    }

        table tr:nth-child(even) {
            background-color: #eee;
        }

        table tr:nth-child(odd) {
            background-color: #fff;
        }

        table th {
            background-color: black;
            color: white;
        }

    p {
        background-color: #eee;
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    table.center {
        margin-left: auto;
        margin-right: auto;
    }

    body {
        text-align: center;
    }

    table {
        margin-left: auto;
        margin-right: auto;
    }
</style>
<body style="background-color:#E6E6FA;">
</body>

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@*@{
    ViewBag.Title = "Home Page";
}*@

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Employee Attendance</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Print", "Print")</li>
                        <li>@Html.ActionLink("LogOut", "LogOut")</li>
                    </ul>
                </div>
            </div>
        </div>
    <div class="container body-content">
        @RenderBody()
        @*<hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>*@
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>